# Generated by Django 2.0.4 on 2018-05-07 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hosts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hostname', models.CharField(max_length=50)),
                ('ip', models.GenericIPAddressField(unique=True)),
                ('mstate', models.CharField(max_length=10)),
            ],
        ),
    ]
