# Generated by Django 2.0.4 on 2018-05-07 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zabbix', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hosts',
            name='mstate',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
