# Generated by Django 2.0.4 on 2018-05-07 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zabbix', '0002_auto_20180507_1825'),
    ]

    operations = [
        migrations.AddField(
            model_name='hosts',
            name='last_time',
            field=models.CharField(blank=True, max_length=12),
        ),
    ]
