# Generated by Django 2.0.4 on 2018-07-04 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zabbix', '0004_auto_20180507_1838'),
    ]

    operations = [
        migrations.CreateModel(
            name='DomainLogs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain_cmds', models.CharField(blank=True, max_length=100)),
                ('user', models.CharField(default='none', max_length=20)),
                ('last_time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Domains',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain', models.CharField(max_length=40)),
                ('domainId', models.CharField(max_length=36)),
                ('domainKey', models.CharField(max_length=32)),
                ('user', models.CharField(default='none', max_length=20)),
                ('last_time', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
